"""Add Reaction model with named constraints

Revision ID: e6d10f598039
Revises: 
Create Date: 2025-10-06 02:41:08.662257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d10f598039'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_reaction_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reaction_post', type_='foreignkey')
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('post_id')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
